const AppImages = {
ONBOARD1: require('../images/onboard1.png'),
ONBOARD2: require('../images/onboard2.png'),
ONBOARD3: require('../images/onboard3.png'),
NXTLEVEL: require('../images/NXTLEVEL.png'),
NEXT: require('../images/Next.png'),
EYE: require('../images/eye.png'),
EYECLOSE: require('../images/eyeclose.png'),
BACK: require('../images/back.png'),
SUCCESS: require('../images/success.png'),
HOME: require('../images/home.png'),
JEEP: require('../images/jeep.png'),
ADDTRIP: require('../images/addTrip.png'),
PROFILE: require('../images/profile.png'),
NOTIF: require('../images/notif.png'),
DOT: require('../images/dot.png'),
SEARCH: require('../images/search.png'),
HOME1: require('../images/home1.png'),
HOME2: require('../images/home2.png'),
SHARE: require('../images/share.png'),
DOWN: require('../images/down.png'),
UP: require('../images/up.png'),
REFRESH: require('../images/refresh.png'),
GROUP: require('../images/group.png'),
DETAILS: require('../images/details.png'),
FILTER: require('../images/Filter.png'),
}

export default AppImages;