export const RouteNames = {
  SplashScreen: 'SplashScreen',
  OnboardScreen: 'OnboardScreen',
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  ForgotPasswordScreen: 'ForgotPasswordScreen',
  ChangePasswordScreen: 'ChangePasswordScreen',
  ResetPasswordScreen: 'ResetPasswordScreen',
  VerificationScreen: 'VerificationScreen',
  SuccessScreen: 'SuccessScreen',
  BottomTabs: 'BottomTabs',
  HomeScreen: 'HomeScreen',
  MyTripScreen: 'MyTripScreen',
  AddTripScreen: 'AddTripScreen',
  ProfileScreen: 'ProfileScreen',
  TripDetails: 'TripDetails',
  SettingsScreen: 'SettingsScreen',
  AboutScreen: 'AboutScreen',
  EditProfile: 'EditProfile',
  AddCar: 'AddCar',
  MarshalList: 'MarshalList',
  UserList: 'UserList',
  TripMembers: 'TripMembers',
  JoinTrip: 'JoinTrip',
  NotificationScreen: 'NotificationScreen',
  BroadcastScreen: 'BroadcastScreen',
  MapScreen: 'MapScreen',
  DeleteAccount: 'DeleteAccount',
  UserPicker:'UserPicker',
  UserTrips: 'UserTrips'
} as const;
